### ISSUE TITLE
9月末までにすること

### ISSUE THREAD

**Issue by asdmay** [asdmay/leap_practice#8]
- node.jsに書き換えて、browserify で変換して動かせるようにする
- 入力したジェスチャを変数に保存しておくようなプログラムをつくる
- 2回ジェスチャを入力したときに1回目と2回目のジェスチャをdtw使って類似度を測る

**Comment by otknoy** [comment]
browserify とかはこの辺が参考になりそう。
- [npmでnode.jsのpackageを管理する](http://qiita.com/sinmetal/items/395edf1d195382cfd8bc)
- [npm とか bower とか一体何なんだよ！Javascript 界隈の文脈を理解しよう](http://qiita.com/megane42/items/2ab6ffd866c3f2fda066)

**Comment by otknoy** [comment]
あと、dtw のリファレンスを読めばおっけー

**Comment by otknoy** [comment]
commit を細かく分けるのと同様に、issue も細かく分けとくといいよー。

**Comment by asdmay** [comment]
9/30現在
- <del>node.jsに書き換えて、browserify で変換して動かせるようにする</del>
- <del>入力したジェスチャを変数に保存しておくようなプログラムをつくる</del>
- 2回ジェスチャを入力したときに1回目と2回目のジェスチャをdtw使って類似度を測る

**Comment by asdmay** [comment]
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

**Comment by asdmay** [comment]
- 2回ジェスチャを入力するのをやめて，正解データ（適当に作ったやつ）と入力ジェスチャの類似度を測るようにする
- dtwをx, y, zごとに使わないといけないらしい
- それぞれdtwを使って類似度測るのできてない

**Comment by otknoy** [comment]
更新しましょう。Close しましょう。新しい Issue を立てましょう。

**Comment by asdmay** [comment]
できたのでCloseします
